// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SubscriptionServiceProcessor.Models;

public partial class BankAccount
{
    public int BankAccountId { get; set; }

    public int UserId { get; set; }

    public string EncryptedAccountNumber { get; set; }

    public string EncryptedRoutingNumber { get; set; }

    public string ValidationStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}