// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SubscriptionServiceProcessor.Models;

public partial class StatusChange
{
    public int ChangeId { get; set; }

    public int SubscriptionId { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public DateTime Timestamp { get; set; }
}