// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SubscriptionServiceProcessor.Models;

public partial class SubscriptionServiceContext : DbContext
{
    public SubscriptionServiceContext(DbContextOptions<SubscriptionServiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BankAccount> BankAccounts { get; set; }

    public virtual DbSet<StatusChange> StatusChanges { get; set; }

    public virtual DbSet<Subscription> Subscriptions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BankAccount>(entity =>
        {
            entity.HasKey(e => e.BankAccountId).HasName("PK__BankAcco__4FC8E4A1F021C772");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.EncryptedAccountNumber)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.EncryptedRoutingNumber)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.ValidationStatus)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<StatusChange>(entity =>
        {
            entity.HasKey(e => e.ChangeId).HasName("PK__StatusCh__0E05C597588C6388");

            entity.Property(e => e.NewStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OldStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Timestamp).HasColumnType("datetime");
        });

        modelBuilder.Entity<Subscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__Subscrip__9A2B249D5D5D43FA");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}